config/routes.rb
Rails.application.routes.draw do
  root 'players#index'
  resources :players
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  	@players = Player.all
  end
def create
@player=player.new(player_params)
if @player.save
redirect_to root_path
end
end

 
  def new
  	@player = Player.new
  	if @player.save

    redirect_to root_path
end
  end

  def show
  	   @player = Player.find_by(id:params[:id])
  end

  def edit
  	@player = Player.find_by(id:params[:id])
  end
  def update
  	@player = Player.find_by(id:params[:id])
  	@plater.update(player_params)
  	if @player.save

    redirect_to player_path(@player.id)
end
  end
  def destroy
  	@player = Player.find_by(id:params[:id])
  	@player.destroy
 
    redirect_to player_path
  end

  public 
   def player_params
    params.require(:player).permit(:nickname, :rank, :charisma, :wisdom)	
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<%= form_for @player, url: players_path(player.id) do |f| %>
<%= f.text_field :nickname %><br/>
<%= f.text_field :rank %><br/>
<%= f.text_field :charisma %><br/>
<%= f.text_field :wisdom %><br/>
<%= f.submit “Create” %>
<% end %>

app/views/players/index.html.erb
<% if @players == [] %>
<p>Create Players</p>
<%else %>
<% @players.each do |player| %>
<p>Nickname: <b> <%= player.nickname %></br>
<%= player.rank %></br>
<%= player.charisma %></br>
<%= player.wisdom %></br>

<%= link_to “Read more”, player_path(player.id) %>

<% end %>
<% end %>
<%= link_to “Create”, new_player_path %>

app/views/players/new.html.erb
<%= form_for @player, url: player_path do |f| %>
<%= f.text_field :nickname %><br/>
<%= f.text_field :rank %><br/>
<%= f.text_field :charisma %><br/>
<%= f.text_field :wisdom %><br/>
<%= f.submit “Create” %>
<% end %>

app/views/players/show.html.erb
<p>
nickname <%= @player.nickname %><br />
Player rank: <%= @player.rank%><br />
Player charisma: <%= @player.charisma %><br />
Player wisdom: <%= @player.wisdom %><br />

</p>
<p>
<%= link_to “Edit”, edit_player_path(@plater.id) %><br />
<%= link_to “Destroy”, player_path(@plater.id), method: :delete %><br />

</p>